### ISSUE TITLE
Clear fields and results when starting a new search

### ISSUE THREAD

**Issue by stsurla** [ICFI/ADS18f_Alpha#10]
![results don t clear](https://cloud.githubusercontent.com/assets/11739352/8292299/f2ca4434-18fc-11e5-8546-e9df4b256eb1.png)

After doing a search, you may want to do a different search. When you start typing in a field, the results should clear. 

This might be done by auto-clearing when the user starts to type (preferable), or by adding a "clear" or "new search" button.

**Comment by icf-jheinrichs** [comment]
Discussed with group and determined to just leave as is. If user testing determines this is confusing we can address again later.
