### ISSUE TITLE
Change field for text response to [interactions_and_usage]

### ISSUE THREAD

**Issue by lindydreyer** [ICFI/ADS18f_Alpha#30]
![screen shot 2015-06-25 at 11 09 41 am](https://cloud.githubusercontent.com/assets/13051362/8357775/a176bcfe-1b2a-11e5-9871-2808beb79bbe.png)

Text response should be included on both yes and no responses. (only yes, as of now)

**Comment by azeswitz** [comment]
Change property used from "spl_medguide" to "message" for paragraph output.  spl_medguide is being populated with the "indications_and_usage" data but will be removed after the front-end change is made.  This was done to prevent front-end breakage due to a change in the API contract.
