### ISSUE TITLE
Test #6 Failed

### ISSUE THREAD

**Issue by KasiaGalica** [ICFI/ADS18f_Alpha#37]
Wellbutrin CAN cause hives. Not sure where this problem is- the metadata does have this.
![screen shot 2015-06-26 at 11 16 43 am](https://cloud.githubusercontent.com/assets/13038216/8381908/d8942a46-1bfc-11e5-8b82-39a07d9284aa.png)

**Comment by icf-jheinrichs** [comment]
hives is not a result in the typeahead. Wouldn't this fall under test case #2?

If it's supposed to - then it'd be a data issue. not sure if that'd be a query update by Steve or API issue for Andy
