### ISSUE TITLE
Add additional language to response

### ISSUE THREAD

**Issue by KasiaGalica** [ICFI/ADS18f_Alpha#57]
Need to add something like this....
-

Not all side effects for "_______" may be reported. Always check with your doctor or healthcare professional for medical advice. Call 911 if this is a medical emergency.

**Comment by lindydreyer** [comment]
Let's use this language:
Everyone reacts differently to medication. Always check with your doctor or healthcare professional for medical advice. <strong>If this is a medical emergency, call 911 immediately.</strong>

**Comment by dpo76** [comment]
Here's the language in action - disregard the charts...
![openfda-effect-result-v1](https://cloud.githubusercontent.com/assets/6741269/8455515/35709ed2-1fd3-11e5-951b-5d414a53d077.png)
