### ISSUE TITLE
Add mouse-over text to "Report Side Effect" Button

### ISSUE THREAD

**Issue by KasiaGalica** [ICFI/ADS18f_Alpha#58]
Add this language: "When you report a side effect to the FDA, you help make medicine safer for everyone."

**Comment by icf-jheinrichs** [comment]
This is done, but isn't a great experience on mobile. can we just put the text below the button?
![screen shot 2015-07-01 at 9 04 48 am](https://cloud.githubusercontent.com/assets/11022978/8456334/59b9a70a-1fd0-11e5-9a15-219ca9b3ddb2.png)

**Comment by KasiaGalica** [comment]
Hm, the design is getting a little text heavy. My instinct says that the mouse over text doesn't need to be there unless it's mouse over....but I'll let the experts make the call. Adding Lindy to see what she thinks.

**Comment by stsurla** [comment]
The purpose of the "When you report" text is to get someone to put their mouse on the Report a Side Effect Button and click it. So I think it needs to be persistent.  Since it crowds up the mobile interface, though, I think it can be omitted from the mobile view.

**Comment by icf-jheinrichs** [comment]
there are no 'mouse over' events on mobile. iOS translates the first touch to a mouse over event. so:

1) user touches button once - tooltip shows up
2a) user touches button again - goes to linked page
2b) user doesn't touch button again - no way to dismiss tooltip.

**Comment by stsurla** [comment]
I see what you mean, Jeff.  I agree that putting the text persistently under the button probably works better for mobile than having the mouseover pasted persistently over the "Search More Side Effects" button. 

However, this is getting in the realm of needing user testing to pick the best course of action. I vote for leaving the mouseover as you've got in now, and having me log a "Do User Testing" issue.  Thoughts?

**Comment by KasiaGalica** [comment]
good thoughts here, I agree with user testing and my other thought is to just take it out if it doesn't work well on mobile- the less text the better.
