### ISSUE TITLE
Limit text return size

### ISSUE THREAD

**Issue by KasiaGalica** [ICFI/ADS18f_Alpha#61]
Limit text size- add "see more" at the bottom ![screen shot 2015-06-30 at 1 41 00 pm](https://cloud.githubusercontent.com/assets/13038216/8437556/b7816182-1f2d-11e5-89b5-9fc84eba84fa.png)

**Comment by icf-jheinrichs** [comment]
I'm not fond of this.

It makes the user take an action to read the full content we're presenting them as the search result. If it's not important enough to show full content, then why is it the main content?

**Comment by jvanderlan** [comment]
Concur with Jeff - are there examples where the returned results extend significantly?

**Comment by KasiaGalica** [comment]
Because we don't have any other text to show there yet. We're not happy with the content completely and yes there are instances where the text extends significantly. E.G. Clarythrimycin causes anxiety.
