### ISSUE TITLE
Changes to "NO" response

### ISSUE THREAD

**Issue by KasiaGalica** [ICFI/ADS18f_Alpha#66]
Replace "no _____ doesn't cause _____" with
 “Sorry, we don’t know if _[med]_____ causes___[symptom]_____"

Keep text pulling from "Indications_and_usage" for the medicine.
Keep "call doctor" and "data unvalidated" disclaimers
Keep "report side effect" and "search more" buttons

Add chart from "yes" response that displays # of times this symptom has been reported as an adverse event.

**Comment by KasiaGalica** [comment]
Not sure why this won't allow me to asssign more than one person

**Comment by dpo76** [comment]
Just discussed with Lindy...
![openfda-effect-result-no-v2](https://cloud.githubusercontent.com/assets/6741269/8460793/8e4eb6c0-1ff5-11e5-9f7c-77688c069dff.png)

**Comment by dpo76** [comment]
Again, don't mind the chart.

**Comment by icf-jheinrichs** [comment]
Header text is updated, as is chart use.

Andy please pass "Indications_and_usage" on no response.

**Comment by KasiaGalica** [comment]
Andy to update response ---no longer need to have "indications_and_usage"    No="show error found false"

**Comment by icf-jheinrichs** [comment]
there will be no {showError: true} response.

expected 'no' response

{
  "found": false
}

expected 'yes' response:

{
  "found": true,
  "brand_name": "OxyContin",
  "generic_name": "OXYCODONE HYDROCHLORIDE",
  "substance_name": "OXYCODONE HYDROCHLORIDE",
  "spl_medguide": [
    "INDICATIONS AND USAGE OxyContin Tablets are a controlled-release oral formulation of oxycodone hydrochloride indicated for the management of moderate to severe pain when a continuous, around-the-clock analgesic is needed for an extended period of time. OxyContin is NOT intended for use as a prn analgesic. Physicians should individualize treatment in every case, initiating therapy at the appropriate point along a progression from non-opioid analgesics, such as non-steroidal anti-inflammatory drugs and acetaminophen to opioids in a plan of pain management such as outlined by the World Health Organization, the Agency for Healthcare Research and Quality (formerly known as the Agency for HealthCare Policy and Research), the Federation of State Medical Boards Model Guidelines, or the American Pain Society. OxyContin is not indicated for pain in the immediate postoperative period (the first 12-24 hours following surgery), or if the pain is mild, or not expected to persist for an extended period of time. OxyContin is only indicated for postoperative use if the patient is already receiving the drug prior to surgery or if the postoperative pain is expected to be moderate to severe and persist for an extended period of time. Physicians should individualize treatment, moving from parenteral to oral analgesics as appropriate. (See American Pain Society guidelines.)"
  ],
  "message": [
    "INDICATIONS AND USAGE OxyContin Tablets are a controlled-release oral formulation of oxycodone hydrochloride indicated for the management of moderate to severe pain when a continuous, around-the-clock analgesic is needed for an extended period of time. OxyContin is NOT intended for use as a prn analgesic. Physicians should individualize treatment in every case, initiating therapy at the appropriate point along a progression from non-opioid analgesics, such as non-steroidal anti-inflammatory drugs and acetaminophen to opioids in a plan of pain management such as outlined by the World Health Organization, the Agency for Healthcare Research and Quality (formerly known as the Agency for HealthCare Policy and Research), the Federation of State Medical Boards Model Guidelines, or the American Pain Society. OxyContin is not indicated for pain in the immediate postoperative period (the first 12-24 hours following surgery), or if the pain is mild, or not expected to persist for an extended period of time. OxyContin is only indicated for postoperative use if the patient is already receiving the drug prior to surgery or if the postoperative pain is expected to be moderate to severe and persist for an extended period of time. Physicians should individualize treatment, moving from parenteral to oral analgesics as appropriate. (See American Pain Society guidelines.)"
  ]
}
